### ISSUE TITLE
Testing Picture in MC-Blur-Dataset has obvious artifact

### ISSUE THREAD

**Issue by four1000** [megvii-research/NAFNet#13]
hi, I use your pretrained models (NAFNet-GoPro-width32/64) with code and env setting provided by your github to run the pictures from dataset MC-Blur-Dataset and many of them get a result with obvious artifact. Would you like to check if the result is same with your research?
![real_hw_IMG_20200831_152243_BURST086_real-test1000_officalNAFNet32](https://user-images.githubusercontent.com/16235048/165074355-b71f7714-4c16-4ae3-9807-8167141f8d17.png)
![real_hw_IMG_20200831_152243_BURST086](https://user-images.githubusercontent.com/16235048/165074357-d65a3bc9-430a-4e14-8ac4-3d724b8a3406.png)

**Comment by four1000** [comment]
Here is my testing dataset extract from MC-Blur-dataset (https://github.com/HDCVLab/MC-Blur-Dataset)
https://drive.google.com/file/d/1Qtmmgi-hxgt3KgDMf-k3CbPI9fYW-nqd/view?usp=sharing

**Comment by mayorx** [comment]
Hi, four1000,

I'm not sure why there is a significant artifact in your case. I download the image and test on the colab demo, here is the result:
![example](https://user-images.githubusercontent.com/27191939/165096752-e1d79cfd-ff69-41b7-be86-5ce5f36c21fa.png)

It does not perform the best result, as the distribution of the GoPro dataset might be quite different from this case.
But it does not contain the artifacts you report.

**Comment by four1000** [comment]
Thanks for your tips. I also try on your colab notebook with this test image above and get the same correct result as yours.
However, the artifact result shows up if I change the pretrained model with the width32 one which is also provided from your github
![下載](https://user-images.githubusercontent.com/16235048/165137578-ff34787c-d542-4b2e-8dee-a953ea767e1c.png)

**Comment by four1000** [comment]
Here are my steps to reproduce this issue:
1. download the pretrained mode on github (NAFNet-GoPro-width32 https://drive.google.com/file/d/1Fr2QadtDCEXg6iwWX8OzeZLbHOx2t5Bj/view?usp=sharing) and upload it on my google driver
2. open the deblur colab notebook (https://colab.research.google.com/drive/1yR2ClVuMefisH12d_srXMhHnHwwA1YmU?usp=sharing)
3. execute notebook block [Git clone [NAFNet] repo]
4. execute notebook block [Set up the enviroment]
5. modify notebook block [Download pretrained models], change the google drive's link to the downloaded model at step 1.
6. execute notebook block [Preparation]
7. modify notebook block [Create Model], replace "opt_path" as 'options/test/GoPro/NAFNet-width32.yml'
8. execute notebook block [1. Upload images], and upload the testing image as above mentioned
9. execute notebook block [Inference]
10. execute notebook block [Visualize (Optional)]

**Comment by mayorx** [comment]
Hi, four1000, 

Thanks for your detailed steps.  It may be because GoPro is limited to a small number of scenes (about 22) and these scenes (and the blur pattern) might be very different from other datasets.
There might be several ways to alleviate this issue,
1). More constraints.
The "overfitting" issue has been discussed in our work,  [NAFSSR](https://arxiv.org/pdf/2204.08714.pdf), e.g.Table 4: The out-of-distribution datasets' performance can be improved by adding regularization.
![截屏2022-04-26 下午1 26 15](https://user-images.githubusercontent.com/27191939/165227861-8d0dfba9-1226-4034-84c4-5f01ae5b6eb4.jpg)

2). Let the model "see" more different scenes. 
The model trained on REDS dataset (240 scenes)  ([pretrain model](https://drive.google.com/file/d/14D4V4raNYIOhETfcuuLI3bGLB-OYIv6X/view?usp=sharing)) performs better on the RHM-250 dataset than the model trained on only 22 scenes. The visualized results could be downloaded [here](https://pan.baidu.com/s/1gWusCb723waXX8S74vCW5g?pwd=rm8g).

For the image above, it works fine:
![real_hw_IMG_20200831_152243_BURST086](https://user-images.githubusercontent.com/27191939/165229176-9414fe73-d123-43cf-af1d-7754f144c81b.png)
But REDS is not perfect (limited scenes, blur distributed differently), ~0.28% of images meet the artifacts in RHM-250 dataset. We will provide a model trained on real-world datasets and it may reduce the artifacts caused by different data distributions.

3). Augmentation,
E.g. [Real-ESRGAN](https://openaccess.thecvf.com/content/ICCV2021W/AIM/papers/Wang_Real-ESRGAN_Training_Real-World_Blind_Super-Resolution_With_Pure_Synthetic_Data_ICCVW_2021_paper.pdf) demonstrates various degradation methods may improve the robustness of the model.
